name: releases

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet build AchievementsEnabler.sln /p:Configuration=Release
    - name: Get version
      id: version
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'AchievementsEnabler.csproj'
        xpath: '//Version'
    - name: Publish to Thunderstore
      env:
        TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
      run: .\tcli.exe publish --package-version "${{ steps.version.outputs.info }}"
    - name: Publish to GitHub
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.version.outputs.info }}
        commit: ${GITHUB_REF##*/}
        allowUpdates: true
        draft: true
        omitBodyDuringUpdate: true
        artifactErrorsFailBuild: true
        artifacts: "build/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
